version: "3"
services:
    api-db:
        ports:
            - 3306:3306
        container_name: api-db
        restart: always
        image: mariadb:10.1.37
        volumes:
            - ./db/ddl:/docker-entrypoint-initdb.d/
            - ./db/volume:/var/lib/mysql
        environment:
            - 'MYSQL_ROOT_PASSWORD=#onadoor'
    api:
        build: 
            context: ../
            dockerfile: ./docker/restapi/Dockerfile
        image: paymentsapp-api:1.0
        depends_on:
            - api-db
        ports:
            - 9080:9080
            - 9443:9443
            - 7777:7777
        container_name: rest-api
        restart: always
        environment:
            - 'DB_NAME=MyPayments_TEST'
            - 'DB_SERVER=api-db'
            - 'DB_PORT=3306'
            - 'DB_USER=web_user'
            - 'DB_PASSWORD=tempid1'