version: "3"
services:
    mariadb:
        ports:
            - '3306:3306'
        container_name: api-db
        restart: always
        volumes:
            - ./db-ddl:/docker-entrypoint-initdb.d/
            - ./db-volume:/var/lib/mysql
        environment:
            - 'MYSQL_ROOT_PASSWORD=#onadoor'
        image: 'mariadb:10.1.37'