-- MySQL Script generated by MySQL Workbench
-- Sun 30 Dec 2018 06:27:38 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MyPayments_TEST
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MyPayments_TEST` ;

-- -----------------------------------------------------
-- Schema MyPayments_TEST
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyPayments_TEST` DEFAULT CHARACTER SET utf8mb4 ;
USE `MyPayments_TEST` ;

-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product` ;

CREATE TABLE IF NOT EXISTS `Product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `payment_due_by` INT(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 76
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `emailId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `User_Product_Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User_Product_Payment` ;

CREATE TABLE IF NOT EXISTS `User_Product_Payment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_id` INT(11) NOT NULL,
  `payment_date` DATE NOT NULL,
  `user_id` INT(11) NOT NULL,
  `payment_term` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Product_Payment_1_idx` (`product_id` ASC),
  INDEX `fk_User_Product_Payment_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_User_Product_Payment_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Product_Payment_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `User_Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User_Products` ;

CREATE TABLE IF NOT EXISTS `User_Products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Products_1_idx` (`user_id` ASC),
  INDEX `fk_User_Products_2_idx` (`product_id` ASC),
  CONSTRAINT `fk_User_Products_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Products_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
