/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package payments.api;

import javax.ws.rs.ApplicationPath;

@ApplicationPath("api/v1")
public class PaymentsAPIApplication {
    
}
